#!/usr/bin/env python

import sys
from twisted.internet import reactor, defer, protocol

class NotificationProtocol(protocol.Protocol):

    def connectionMade(self):
        
        self.transport.write('test\n')
        self.transport.loseConnection()

def makeHttpFactory():
    factory = protocol.Factory()
    factory.protocol = NotificationProtocol
    return factory

def main(args):
    """ start the main server 
    args: 
        <port> 
    """

    print('Starting server')
    factory = makeHttpFactory()
    reactor.listenTCP(int(args[0]), factory)
    reactor.run()
    print('Stopping server')


if __name__ == "__main__":
    main(sys.argv[1:])
